### ISSUE TITLE
Event for the Drupal 8 Launch party

### ISSUE THREAD

**Issue by meelijane** [drupalmel/drupalmel#16]
November 20th, venue TBC. Starting ~7pm, drinks and canapes, networking, D8FAQ +more.

**Comment by Decipher** [comment]
Events are scraped from Meetup.com, when the meetup.com event is posted it will show on site.

**Comment by meelijane** [comment]
ah, ok, we should make sure it's on meetup then, will add that to our tasks, thanks!
