### ISSUE TITLE
Fix feeds curl issue during CI builds

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drupalmel/drupalmel#31]
Almost each second build is failing right now due to the problem below:

![job__34_2_-_drupalmel_drupalmel_-_travis_ci](https://cloud.githubusercontent.com/assets/378794/11503363/43744134-9894-11e5-827f-3f29c805c398.png)

**Comment by Decipher** [comment]
Marking as duplicate (even though it was created earlier) of #33.
